const castOutNines = (a, b, r) => {
  a = a.toString().split('');
  console.log(`a: ${a}`);
  b = b.toString().split('');
  console.log(`b: ${b}`);
  r = r.toString().split('');
  console.log(`r: ${r}`);
  let a2 = 0;
  a.forEach(i => (a2 += parseFloat(i)));
  console.log(`a2: ${a2}`);
  let b2 = 0;
  b.forEach(i => (b2 += parseFloat(i)));
  console.log(`b2: ${b2}`);
  let r2 = 0;
  r.forEach(i => (r2 += parseFloat(i)));
  console.log(`r2: ${r2}`);
  a2 = a2.toString().split('');
  console.log(`a2: ${a2}`);
  b2 = b2.toString().split('');
  console.log(`b2: ${b2}`);
  r2 = r2.toString().split('');
  console.log(`r2: ${r2}`);
  let a3 = 0;
  a2.forEach(i => (a3 += parseFloat(i)));
  console.log(`a3: ${a3}`);
  let b3 = 0;
  b2.forEach(i => (b3 += parseFloat(i)));
  console.log(`b3: ${b3}`);
  let r3 = 0;
  r2.forEach(i => (r3 += parseFloat(i)));
  console.log(`r3: ${r3}`);
  let last = parseFloat(a3) * parseFloat(b3);
  console.log(`last: ${last}`);
  last = last.toString().split('');
  console.log(`last: ${last}`);
  let last2 = 0;
  last.forEach(i => (last2 += parseFloat(i)));
  console.log(`last2: ${last2}`);
  last2 = last2.toString().split('');
  console.log(`last2: ${last2}`);
  let last3 = 0;
  last2.forEach(i => (last3 += parseFloat(i)));
  console.log(`last3: ${last3}`);
  console.log(`${a3}, ${b3}, ${r3}, ${last3}`);
};

castOutNines(9, 9, 666);
